name: Example - App Control Panel

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name to control'
        required: true
        default: 'invoicer'
      action:
        description: 'Action to perform'
        required: true
        default: 'restart'
        type: choice
        options:
          - status
          - start
          - stop
          - restart
      disable_ssl:
        description: 'Disable SSL verification'
        required: false
        default: false
        type: boolean

jobs:
  app-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Control App
        id: control
        uses: ./
        with:
          truenas-url: ${{ secrets.TRUENAS_URL }}
          api-key: ${{ secrets.TRUENAS_API_KEY }}
          app-name: ${{ github.event.inputs.app_name }}
          action: ${{ github.event.inputs.action }}
          disable-ssl-verify: ${{ github.event.inputs.disable_ssl }}

      - name: Show Results
        run: |
          echo "=== App Control Results ==="
          echo "App: ${{ github.event.inputs.app_name }}"
          echo "Action: ${{ github.event.inputs.action }}"
          echo "Final Status: ${{ steps.control.outputs.app-status }}"
          echo "Success: ${{ steps.control.outputs.success }}"
          echo "=========================="
          
          if [ "${{ steps.control.outputs.success }}" = "true" ]; then
            echo "✅ Action completed successfully"
          else
            echo "❌ Action failed"
            exit 1
          fi

      - name: Send Notification (Optional)
        if: github.event.inputs.action == 'restart' && steps.control.outputs.success == 'true'
        run: |
          echo "🔄 App '${{ github.event.inputs.app_name }}' has been restarted successfully"
          echo "📊 Final status: ${{ steps.control.outputs.app-status }}" 